-- Demo content for CV Portfolio (generated by scripts/generate-seed.ts).
-- Run AFTER all files in supabase/migrations (0001 – 0005).
-- Safe to re-run: it clears content tables first. Messages and admins are untouched.
begin;
truncate public.site_settings, public.profile, public.services, public.projects, public.resume_items,
  public.skills, public.testimonials, public.clients, public.pricing_plans, public.blog_posts, public.awards,
  public.stats, public.process_steps;

insert into public.site_settings (website_name, logo_url, accent_color, accent_color_2, default_theme, contact_email, public_phone, seo_title, seo_description, footer_text, hire_label, sections, map_embed_url, cursor_enabled) values
  ('Julian', null, '#f2b35b', '#f2b35b', 'dark', 'hello@julianhart.demo', '+49 30 1234 5678', 'Julian Hart — Web Developer & UI Designer', 'Julian Hart is a web developer and UI designer in Berlin building fast, beautiful websites and web apps for brands and startups.', 'Web developer & UI designer', 'Hire Me', '[]'::jsonb, 'https://www.openstreetmap.org/export/embed.html?bbox=13.3050%2C52.4870%2C13.5050%2C52.5570&layer=mapnik&marker=52.5200%2C13.4050', true);

insert into public.profile (full_name, professional_title, typed_roles, short_intro, bio, email, phone, location, profile_image_url, hero_image_url, hero_headline, hero_background_url, resume_url, availability_status, trust_line, about_title, about_image_url, about_points, experience_years, work_photos, personal_info, social_links, skill_tools) values
  ('Julian Hart', 'Web Developer & UI Designer', array['Web Developer', 'UI Designer', 'Freelancer', 'Photographer']::text[], 'Creative developer based in Berlin, building fast and beautiful websites for brands, startups and people who love good design.', 'Hi, my name is Julian Hart. I have been designing and building websites for more than eight years, from simple landing pages to complete web apps with dashboards and online payments.

I love taking an idea from a rough sketch to a polished product. Clean code, clear design and fast pages are what I care about most — so my clients can focus on their business while their website quietly does its job.', 'hello@julianhart.demo', '+49 30 1234 5678', 'Berlin, Germany', '/demo/avatar-owner.svg', '/demo/portrait.svg', '', null, '/demo/julian-hart-cv.pdf', 'Available for freelance work', '', '', '/demo/about-wide.svg', array[]::text[], 8, '[]'::jsonb, '[{"label":"Birthday","value":"14.03.1994"},{"label":"Age","value":"32"},{"label":"Address","value":"Torstraße 18, Berlin"},{"label":"Email","value":"hello@julianhart.demo"},{"label":"Phone","value":"+49 30 1234 5678"},{"label":"Nationality","value":"German"},{"label":"Study","value":"TU Berlin"},{"label":"Degree","value":"Master"},{"label":"Interest","value":"Photography, Cycling"},{"label":"Freelance","value":"Available"}]'::jsonb, '[{"platform":"facebook","url":"https://facebook.com/"},{"platform":"x","url":"https://x.com/"},{"platform":"instagram","url":"https://instagram.com/"},{"platform":"dribbble","url":"https://dribbble.com/"},{"platform":"github","url":"https://github.com/"}]'::jsonb, '[]'::jsonb);

insert into public.services (title, short_description, icon_key, active, sort_order) values
  ('Web Development', 'Fast, secure websites and web apps built with modern tools and easy to update from a dashboard.', 'monitor', true, 1),
  ('UI / UX Design', 'Clean, modern interfaces designed around your users, from wireframes to polished screens.', 'layers', true, 2),
  ('Mobile Friendly', 'Every page looks great and works smoothly on phones, tablets and large screens.', 'mobile', true, 3),
  ('Branding', 'Logo, colours and a consistent visual style that make your brand easy to remember.', 'palette', true, 4),
  ('SEO Optimisation', 'Solid technical SEO, fast loading and clear structure so people find you on Google.', 'search', true, 5),
  ('Photography', 'Portraits and product photos that give your website a real, personal feel.', 'camera', true, 6);

insert into public.projects (title, slug, category, year, client, role, intro, challenge, solution, result, cover_image_url, gallery, live_url, likes, featured, status, sort_order) values
  ('Summit Outdoor Store', 'summit-outdoor-store', 'Web Design', 2026, 'Summit Gear', 'Design & Development', 'An online store for outdoor gear with quick checkout and a trip journal.', 'The client had a great product but an outdated website that was slow on mobile and hard to update. Visitors left before they understood what the product did.', 'We rewrote the key messages, designed a clean mobile-first layout and built it with a fast, modern stack. A simple dashboard lets the team edit every section on their own.', 'Pages now load in under a second, bounce rate dropped by a third and the team publishes new content every week without a developer.', '/demo/pf-mountains.svg', '["/demo/pf-mountains.svg","/demo/pf-workspace.svg"]'::jsonb, 'https://example.com', 240, true, 'published', 1),
  ('Lens & Light Studio', 'lens-and-light-studio', 'Photography', 2026, 'Lens & Light', 'Photography, Website', 'Portfolio website and photo shoot for a small photography studio.', 'The client had a great product but an outdated website that was slow on mobile and hard to update. Visitors left before they understood what the product did.', 'We rewrote the key messages, designed a clean mobile-first layout and built it with a fast, modern stack. A simple dashboard lets the team edit every section on their own.', 'Pages now load in under a second, bounce rate dropped by a third and the team publishes new content every week without a developer.', '/demo/pf-camera.svg', '["/demo/pf-camera.svg","/demo/pf-architecture.svg"]'::jsonb, null, 310, true, 'published', 2),
  ('Nord Coffee Identity', 'nord-coffee-identity', 'Branding', 2025, 'Nord Coffee', 'Brand Identity', 'Logo, packaging and a calm Nordic visual style for a speciality coffee brand.', 'The client had a great product but an outdated website that was slow on mobile and hard to update. Visitors left before they understood what the product did.', 'We rewrote the key messages, designed a clean mobile-first layout and built it with a fast, modern stack. A simple dashboard lets the team edit every section on their own.', 'Pages now load in under a second, bounce rate dropped by a third and the team publishes new content every week without a developer.', '/demo/pf-brand.svg', '["/demo/pf-brand.svg","/demo/pf-mobile.svg"]'::jsonb, null, 180, false, 'published', 3),
  ('Pulse Fitness App', 'pulse-fitness-app', 'Mobile App', 2025, 'Pulse', 'UI/UX Design', 'A workout tracker app with habit streaks and simple progress charts.', 'The client had a great product but an outdated website that was slow on mobile and hard to update. Visitors left before they understood what the product did.', 'We rewrote the key messages, designed a clean mobile-first layout and built it with a fast, modern stack. A simple dashboard lets the team edit every section on their own.', 'Pages now load in under a second, bounce rate dropped by a third and the team publishes new content every week without a developer.', '/demo/pf-mobile.svg', '["/demo/pf-mobile.svg","/demo/pf-brand.svg"]'::jsonb, 'https://example.com', 275, false, 'published', 4),
  ('Atlas Architects', 'atlas-architects', 'Web Design', 2024, 'Atlas Architects', 'Design & Development', 'A minimal portfolio website for an architecture office with large project galleries.', 'The client had a great product but an outdated website that was slow on mobile and hard to update. Visitors left before they understood what the product did.', 'We rewrote the key messages, designed a clean mobile-first layout and built it with a fast, modern stack. A simple dashboard lets the team edit every section on their own.', 'Pages now load in under a second, bounce rate dropped by a third and the team publishes new content every week without a developer.', '/demo/pf-architecture.svg', '["/demo/pf-architecture.svg","/demo/pf-mountains.svg"]'::jsonb, null, 205, false, 'published', 5),
  ('Remote Desk Dashboard', 'remote-desk-dashboard', 'Web Design', 2024, 'Remote Desk', 'Front-end Development', 'A booking dashboard for a co-working space with live desk availability.', 'The client had a great product but an outdated website that was slow on mobile and hard to update. Visitors left before they understood what the product did.', 'We rewrote the key messages, designed a clean mobile-first layout and built it with a fast, modern stack. A simple dashboard lets the team edit every section on their own.', 'Pages now load in under a second, bounce rate dropped by a third and the team publishes new content every week without a developer.', '/demo/pf-workspace.svg', '["/demo/pf-workspace.svg","/demo/pf-camera.svg"]'::jsonb, null, 190, false, 'published', 6);

insert into public.resume_items (type, title, subtitle, period, badge, description, active, sort_order) values
  ('experience', 'Freelance Web Developer', 'Self-employed — Berlin', '2022 – Present', null, 'Websites, web apps and brand design for startups and small businesses across Europe.', true, 1),
  ('experience', 'Senior Front-end Developer', 'Pixelwerk Agency', '2019 – 2022', null, 'Led front-end work for e-commerce and SaaS clients and mentored two junior developers.', true, 2),
  ('experience', 'Web Designer', 'Studio Nord', '2017 – 2019', null, 'Designed and built landing pages, email templates and brand assets.', true, 3),
  ('education', 'Master in Computer Science', 'TU Berlin', '2015 – 2017', null, 'Focus on human–computer interaction and web technologies.', true, 1),
  ('education', 'Bachelor in Media Design', 'HTW Berlin', '2012 – 2015', null, 'Typography, visual design, photography and interactive media.', true, 2),
  ('education', 'UX Design Certificate', 'Interaction Design Foundation', '2020', null, 'User research, usability testing and design systems.', true, 3);

insert into public.skills (name, category, display, level, active, sort_order) values
  ('HTML & CSS', 'Programming Skills', 'bar', 95, true, 1),
  ('JavaScript / TypeScript', 'Programming Skills', 'bar', 88, true, 2),
  ('React & Next.js', 'Programming Skills', 'bar', 85, true, 3),
  ('Figma', 'Design Skills', 'bar', 90, true, 4),
  ('Photoshop', 'Design Skills', 'bar', 78, true, 5),
  ('Branding', 'Design Skills', 'bar', 72, true, 6),
  ('German', 'Language Skills', 'circle', 100, true, 7),
  ('English', 'Language Skills', 'circle', 90, true, 8),
  ('Spanish', 'Language Skills', 'circle', 55, true, 9),
  ('Website hosting', 'Knowledge', 'tag', 0, true, 10),
  ('iOS and Android apps', 'Knowledge', 'tag', 0, true, 11),
  ('Create logo design', 'Knowledge', 'tag', 0, true, 12),
  ('Design for print', 'Knowledge', 'tag', 0, true, 13),
  ('Modern and mobile-ready', 'Knowledge', 'tag', 0, true, 14),
  ('Advertising services', 'Knowledge', 'tag', 0, true, 15);

insert into public.testimonials (name, role, company, project_title, quote, avatar_url, rating, active, sort_order) values
  ('Sofia Lindqvist', 'Founder', 'Nord Coffee', 'Brand Identity', 'Julian understood our brand from the first call. The new identity and website feel exactly like us — calm, simple and warm.', '/demo/avatar-1.svg', 5, true, 1),
  ('Marcus Bell', 'CEO', 'Summit Gear', 'Online Store', 'Fast, reliable and full of good ideas. Our online sales grew 35% in the first three months after launch.', '/demo/avatar-2.svg', 5, true, 2),
  ('Emma Novak', 'Product Manager', 'Pulse', 'Fitness App', 'The app design is clean and easy to use. Julian was always on time and explained every decision clearly.', '/demo/avatar-3.svg', 5, true, 3);

insert into public.clients (name, category, logo_url, website_url, active, sort_order) values
  ('Nord', 'Brand', '/demo/logo-nord.svg', null, true, 1),
  ('Atlas', 'Brand', '/demo/logo-atlas.svg', null, true, 2),
  ('Lumen', 'Brand', '/demo/logo-lumen.svg', null, true, 3),
  ('Kite', 'Brand', '/demo/logo-kite.svg', null, true, 4),
  ('Orbit', 'Brand', '/demo/logo-orbit.svg', null, true, 5),
  ('Vela', 'Brand', '/demo/logo-vela.svg', null, true, 6);

insert into public.awards (title, organization, year, short_description, image_url, link_url, active, sort_order) values
  ('Site of the Day', 'Awwwards', '2026', 'For the Summit Outdoor Store website — design, usability and creativity.', '/demo/award-1.svg', null, true, 1),
  ('Top Rated Freelancer', 'Upwork', '2025', 'Top 3% of freelancers for five-star client feedback and on-time delivery.', '/demo/award-2.svg', null, true, 2),
  ('Certified UX Designer', 'IxDF', '2024', 'Professional certificate in user experience and interaction design.', '/demo/award-3.svg', null, true, 3);

insert into public.pricing_plans (name, tagline, price, period, description, features, cta_label, highlighted, active, sort_order) values
  ('Basic', 'Landing page', '$690', 'one-time', 'A single, beautiful page to present you or your product.', array['1 responsive page', 'Contact form', 'Basic SEO', '5-day delivery']::text[], 'Choose Plan', false, true, 1),
  ('Standard', 'Most popular', '$1,900', 'one-time', 'A complete website with admin dashboard, blog and SEO.', array['Up to 6 pages', 'Admin dashboard', 'Blog & SEO setup', 'Speed optimisation', '30 days support']::text[], 'Choose Plan', true, true, 2),
  ('Premium', 'Web app', '$4,500', 'starting from', 'Custom web apps with accounts, payments and integrations.', array['Custom features', 'User accounts', 'Online payments', 'API integrations', '90 days support']::text[], 'Choose Plan', false, true, 3);

insert into public.blog_posts (title, slug, excerpt, content, cover_image_url, category, read_time, published_at, status) values
  ('Format releases a new tool that makes portfolio hosting simple', 'new-tool-portfolio-hosting', 'A quick look at the new wave of simple hosting tools for designers and developers — and what they mean for your portfolio.', 'Hosting a portfolio used to mean servers, FTP and a lot of patience. Today it takes a few clicks.

## Why it matters
Your portfolio is often the first thing a client sees. If it is slow or broken, you lose the job before the first call.

## What to look for
- Automatic HTTPS
- Deploys from GitHub
- A free plan for small sites

## My setup
I use Next.js, a small database for content and a hosting platform that deploys every push automatically. Updates take seconds, not hours.', '/demo/news-sneakers.svg', 'Tools', '4 min read', '2026-09-18', 'published'),
  ('How I find direction when starting a new design', 'finding-direction-new-design', 'Blank canvas? These five questions help me pick a clear direction before I open Figma.', 'Every project starts with a blank page. These questions help me move forward quickly.

## 1. Who is it for?
A website for teenagers looks very different from one for lawyers.

## 2. What is the one action?
Book a call, buy a product, read an article — pick one.

## 3. What should it feel like?
Three words, for example calm, bold and friendly.

## 4. What do competitors do?
Look, learn and then do something different.

## 5. What content exists?
Design around real text and photos, never lorem ipsum.', '/demo/news-compass.svg', 'Design', '5 min read', '2026-09-02', 'published'),
  ('Why small details make websites feel alive', 'small-details-websites-alive', 'Hover effects, smooth scrolling and a custom cursor — small touches that make a big difference.', 'Good websites are not only about layout and colour. Small details make them feel alive.

## Motion with purpose
Animations should guide the eye, not distract it. Keep them short and smooth.

## Feedback everywhere
Buttons that react, forms that confirm and links that change on hover all tell users the site is listening.

## Respect the user
Always turn heavy motion off for people who prefer reduced motion in their system settings.', '/demo/news-cat.svg', 'Web Design', '3 min read', '2026-08-20', 'published'),
  ('A calm home studio setup for focused work', 'calm-home-studio-setup', 'The simple desk, light and tools I use every day to stay focused while working from home.', 'A good workspace does not need to be expensive. It needs to be calm.

## Light
Warm, indirect light in the evening and daylight during the day.

## One screen
A single large monitor keeps me focused on one task at a time.

## Sound
Good headphones and a simple playlist without lyrics.

## Routine
The same start time and a short walk before work make the biggest difference of all.', '/demo/news-studio.svg', 'Lifestyle', '3 min read', '2026-08-04', 'published');

insert into public.stats (value, label, placement, percent, active, sort_order) values
  ('8+', 'Years of experience', 'band', 0, true, 1),
  ('140+', 'Projects completed', 'band', 0, true, 2),
  ('90+', 'Happy clients', 'band', 0, true, 3),
  ('12', 'Awards won', 'band', 0, true, 4);

insert into public.process_steps (title, description, active, sort_order) values
  ('Discuss', 'A short call to understand your goals, audience and budget.', true, 1),
  ('Design', 'Wireframes and visual design you can review and comment on.', true, 2),
  ('Develop', 'Clean, fast code with weekly previews on a live link.', true, 3),
  ('Launch', 'Go live, then support and small updates when you need them.', true, 4);

commit;

-- ------------------------------------------------------------------
-- Make your dashboard owner (run once, after creating the user in
-- Supabase -> Authentication -> Users). Replace the email below.
-- ------------------------------------------------------------------
-- insert into public.admins (user_id, display_name)
-- select id, 'Julian Hart' from auth.users where email = 'owner@example.com'
-- on conflict (user_id) do update set active = true;
