-- =====================================================================
-- Website installed into schema "site04" (generated by scripts/build-schema-sql.mjs).
-- Storage bucket: "site04-media".
-- WARNING: run this file ONCE. Running it again replaces all website content with the demo content
-- (messages and admins are kept).
--
-- AFTER running this file:
--   1. Project Settings → Data API → "Exposed schemas": add site04  (then Save)
--   2. Website .env: NEXT_PUBLIC_SUPABASE_SCHEMA=site04
--   3. Make your owner an admin of this website (bottom of this file).
-- =====================================================================

create schema if not exists site04;
grant usage on schema site04 to anon, authenticated, service_role;
alter default privileges in schema site04 grant all on tables to anon, authenticated, service_role;
alter default privileges in schema site04 grant all on sequences to anon, authenticated, service_role;
alter default privileges in schema site04 grant execute on functions to anon, authenticated, service_role;
-- Row Level Security (enabled on every table below) still decides who can read or write.

-- >>> 0001_init.sql
-- =====================================================================
-- Business Portfolio — initial schema
-- Single-owner portfolio. Public can read published/active content;
-- only users listed in site04.admins (and active) can write.
-- =====================================================================


-- ---------- helpers ----------
create or replace function site04.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- ---------- admins (dashboard users) ----------
create table if not exists site04.admins (
  user_id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null default 'Owner',
  avatar_url text,
  role text not null default 'owner' check (role in ('owner')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function site04.is_admin()
returns boolean
language sql stable security definer set search_path = site04
as $$
  select exists (
    select 1 from site04.admins a where a.user_id = auth.uid() and a.active
  );
$$;
revoke all on function site04.is_admin() from public;
grant execute on function site04.is_admin() to anon, authenticated;

-- ---------- site settings (single row) ----------
create table if not exists site04.site_settings (
  id uuid primary key default gen_random_uuid(),
  website_name text not null,
  logo_url text,
  accent_color text not null default '#ff014f' check (accent_color ~* '^#([0-9a-f]{3}|[0-9a-f]{6})$'),
  default_theme text not null default 'dark' check (default_theme in ('dark', 'light', 'system')),
  contact_email text not null,
  public_phone text,
  seo_title text not null,
  seo_description text not null,
  footer_text text not null default '',
  hire_label text not null default 'Hire Me',
  updated_at timestamptz not null default now()
);

-- ---------- profile (single row) ----------
create table if not exists site04.profile (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  professional_title text not null,
  typed_roles text[] not null default '{}',
  short_intro text not null default '',
  bio text not null default '',
  email text not null,
  phone text,
  location text not null default '',
  profile_image_url text not null,
  hero_image_url text,
  resume_url text,
  availability_status text not null default '',
  social_links jsonb not null default '[]'::jsonb,
  skill_tools jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- content tables ----------
create table if not exists site04.services (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  short_description text not null,
  icon_key text,
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site04.projects (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  category text not null,
  year int not null,
  client text,
  role text,
  intro text not null,
  challenge text,
  solution text,
  result text,
  cover_image_url text not null,
  gallery jsonb not null default '[]'::jsonb,
  live_url text,
  likes int not null default 0,
  featured boolean not null default false,
  status text not null default 'published' check (status in ('published', 'draft')),
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site04.resume_items (
  id uuid primary key default gen_random_uuid(),
  type text not null check (type in ('education', 'experience')),
  title text not null,
  subtitle text not null,
  period text not null,
  badge text,
  description text not null default '',
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site04.skills (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null,
  level int not null default 80 check (level between 0 and 100),
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site04.testimonials (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  role text,
  company text,
  project_title text,
  quote text not null,
  avatar_url text,
  rating int not null default 5 check (rating between 1 and 5),
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site04.clients (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null default 'Brand',
  logo_url text,
  website_url text,
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site04.pricing_plans (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  tagline text not null default '',
  price text not null,
  period text not null default '',
  description text not null default '',
  features text[] not null default '{}',
  cta_label text not null default 'Order Now',
  highlighted boolean not null default false,
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site04.blog_posts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  excerpt text not null,
  content text not null,
  cover_image_url text not null,
  category text not null,
  read_time text not null default '3 min read',
  published_at date not null default current_date,
  status text not null default 'published' check (status in ('published', 'draft')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site04.messages (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 80),
  email text not null check (char_length(email) between 5 and 120),
  phone text check (phone is null or char_length(phone) <= 30),
  service text check (service is null or char_length(service) <= 80),
  budget text check (budget is null or char_length(budget) <= 40),
  message text not null check (char_length(message) between 10 and 4000),
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

-- ---------- updated_at triggers ----------
do $$
declare t text;
begin
  foreach t in array array['admins','site_settings','profile','services','projects','resume_items','skills','testimonials','clients','pricing_plans','blog_posts']
  loop
    execute format('drop trigger if exists trg_%1$s_updated on site04.%1$s', t);
    execute format('create trigger trg_%1$s_updated before update on site04.%1$s for each row execute function site04.set_updated_at()', t);
  end loop;
end $$;

-- ---------- Row Level Security ----------
alter table site04.admins enable row level security;
alter table site04.site_settings enable row level security;
alter table site04.profile enable row level security;
alter table site04.services enable row level security;
alter table site04.projects enable row level security;
alter table site04.resume_items enable row level security;
alter table site04.skills enable row level security;
alter table site04.testimonials enable row level security;
alter table site04.clients enable row level security;
alter table site04.pricing_plans enable row level security;
alter table site04.blog_posts enable row level security;
alter table site04.messages enable row level security;

-- admins: a user can read and update only their own row (never role/active via app)
drop policy if exists "admins read self" on site04.admins;
create policy "admins read self" on site04.admins for select to authenticated using (user_id = auth.uid());
drop policy if exists "admins update self" on site04.admins;
create policy "admins update self" on site04.admins for update to authenticated
  using (user_id = auth.uid() and site04.is_admin())
  with check (user_id = auth.uid() and role = 'owner' and active = true);

-- public read policies
drop policy if exists "public read settings" on site04.site_settings;
create policy "public read settings" on site04.site_settings for select using (true);
drop policy if exists "public read profile" on site04.profile;
create policy "public read profile" on site04.profile for select using (true);
drop policy if exists "public read services" on site04.services;
create policy "public read services" on site04.services for select using (active or site04.is_admin());
drop policy if exists "public read projects" on site04.projects;
create policy "public read projects" on site04.projects for select using (status = 'published' or site04.is_admin());
drop policy if exists "public read resume" on site04.resume_items;
create policy "public read resume" on site04.resume_items for select using (active or site04.is_admin());
drop policy if exists "public read skills" on site04.skills;
create policy "public read skills" on site04.skills for select using (active or site04.is_admin());
drop policy if exists "public read testimonials" on site04.testimonials;
create policy "public read testimonials" on site04.testimonials for select using (active or site04.is_admin());
drop policy if exists "public read clients" on site04.clients;
create policy "public read clients" on site04.clients for select using (active or site04.is_admin());
drop policy if exists "public read pricing" on site04.pricing_plans;
create policy "public read pricing" on site04.pricing_plans for select using (active or site04.is_admin());
drop policy if exists "public read posts" on site04.blog_posts;
create policy "public read posts" on site04.blog_posts for select using (status = 'published' or site04.is_admin());

-- admin write policies
do $$
declare t text;
begin
  foreach t in array array['site_settings','profile','services','projects','resume_items','skills','testimonials','clients','pricing_plans','blog_posts']
  loop
    execute format('drop policy if exists "admin insert %1$s" on site04.%1$s', t);
    execute format('create policy "admin insert %1$s" on site04.%1$s for insert to authenticated with check (site04.is_admin())', t);
    execute format('drop policy if exists "admin update %1$s" on site04.%1$s', t);
    execute format('create policy "admin update %1$s" on site04.%1$s for update to authenticated using (site04.is_admin()) with check (site04.is_admin())', t);
    execute format('drop policy if exists "admin delete %1$s" on site04.%1$s', t);
    execute format('create policy "admin delete %1$s" on site04.%1$s for delete to authenticated using (site04.is_admin())', t);
  end loop;
end $$;

-- messages: anyone may submit (validated by CHECK constraints); only admins can read/manage
drop policy if exists "anyone can send message" on site04.messages;
create policy "anyone can send message" on site04.messages for insert to anon, authenticated with check (is_read = false);
drop policy if exists "admin read messages" on site04.messages;
create policy "admin read messages" on site04.messages for select to authenticated using (site04.is_admin());
drop policy if exists "admin update messages" on site04.messages;
create policy "admin update messages" on site04.messages for update to authenticated using (site04.is_admin()) with check (site04.is_admin());
drop policy if exists "admin delete messages" on site04.messages;
create policy "admin delete messages" on site04.messages for delete to authenticated using (site04.is_admin());

-- ---------- Storage ----------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'site04-media',
  'site04-media',
  true,
  5242880, -- 5 MB
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif', 'application/pdf']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public read media [site04]" on storage.objects;
create policy "public read media [site04]" on storage.objects for select using (bucket_id = 'site04-media');
drop policy if exists "admin upload media [site04]" on storage.objects;
create policy "admin upload media [site04]" on storage.objects for insert to authenticated
  with check (bucket_id = 'site04-media' and site04.is_admin()
    and (storage.foldername(name))[1] in ('profile', 'projects', 'services', 'testimonials', 'clients', 'blog', 'documents', 'settings'));
drop policy if exists "admin update media [site04]" on storage.objects;
create policy "admin update media [site04]" on storage.objects for update to authenticated
  using (bucket_id = 'site04-media' and site04.is_admin());
drop policy if exists "admin delete media [site04]" on storage.objects;
create policy "admin delete media [site04]" on storage.objects for delete to authenticated
  using (bucket_id = 'site04-media' and site04.is_admin());


-- >>> 0002_hardening.sql
-- =====================================================================
-- Security hardening (run after 0001_init.sql). Safe to re-run.
-- =====================================================================

-- ---------- Contact form: database-level anti-spam ----------
-- The anon key is public, so someone could call the REST API directly and
-- skip the website's rate limit. This trigger caps volume in the database.
create or replace function site04.messages_guard()
returns trigger
language plpgsql security definer set search_path = site04
as $$
begin
  -- Clients can never set these themselves.
  new.is_read := false;
  new.created_at := now();

  if (select count(*) from site04.messages where created_at > now() - interval '10 minutes') >= 30 then
    raise exception 'Too many messages right now. Please try again later.' using errcode = 'P0001';
  end if;

  if (select count(*) from site04.messages
      where lower(email) = lower(new.email) and created_at > now() - interval '1 hour') >= 3 then
    raise exception 'Too many messages from this email. Please try again later.' using errcode = 'P0001';
  end if;

  if new.email !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception 'Invalid email.' using errcode = 'P0001';
  end if;

  return new;
end $$;

drop trigger if exists trg_messages_guard on site04.messages;
create trigger trg_messages_guard before insert on site04.messages
for each row execute function site04.messages_guard();

create index if not exists messages_created_at_idx on site04.messages (created_at desc);
create index if not exists messages_email_idx on site04.messages (lower(email));

-- ---------- Storage: stop public listing of files ----------
-- Public buckets serve files by URL without any SELECT policy, so only
-- admins need to list objects (the dashboard uses it to delete old files).
drop policy if exists "public read media [site04]" on storage.objects;
drop policy if exists "admin read media [site04]" on storage.objects;
drop policy if exists "admin read media [site04]" on storage.objects;
create policy "admin read media [site04]" on storage.objects for select to authenticated
  using (bucket_id = 'site04-media' and site04.is_admin());

-- ---------- Admins: users may only edit their name / avatar ----------
revoke update on site04.admins from anon, authenticated;
grant update (display_name, avatar_url) on site04.admins to authenticated;


-- >>> 0003_awards_sections.sql
-- =====================================================================
-- Awards + page-section settings (run after 0002_hardening.sql). Safe to re-run.
-- =====================================================================

-- ---------- Awards (optional section) ----------
create table if not exists site04.awards (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  organization text,
  year text,
  short_description text not null,
  image_url text not null,
  link_url text,
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_awards_updated on site04.awards;
create trigger trg_awards_updated before update on site04.awards
for each row execute function site04.set_updated_at();

alter table site04.awards enable row level security;

drop policy if exists "public read awards" on site04.awards;
drop policy if exists "admin insert awards" on site04.awards;
drop policy if exists "admin update awards" on site04.awards;
drop policy if exists "admin delete awards" on site04.awards;
drop policy if exists "public read awards" on site04.awards;
create policy "public read awards" on site04.awards for select using (active or site04.is_admin());
drop policy if exists "admin insert awards" on site04.awards;
create policy "admin insert awards" on site04.awards for insert to authenticated with check (site04.is_admin());
drop policy if exists "admin update awards" on site04.awards;
create policy "admin update awards" on site04.awards for update to authenticated using (site04.is_admin()) with check (site04.is_admin());
drop policy if exists "admin delete awards" on site04.awards;
create policy "admin delete awards" on site04.awards for delete to authenticated using (site04.is_admin());

-- ---------- Page sections: visibility + order ----------
alter table site04.site_settings
  add column if not exists sections jsonb not null default '[]'::jsonb;

-- ---------- Storage: allow the new "awards" upload folder ----------
drop policy if exists "admin upload media [site04]" on storage.objects;
drop policy if exists "admin upload media [site04]" on storage.objects;
create policy "admin upload media [site04]" on storage.objects for insert to authenticated
  with check (bucket_id = 'site04-media' and site04.is_admin()
    and (storage.foldername(name))[1] in ('profile', 'projects', 'services', 'testimonials', 'clients', 'awards', 'blog', 'documents', 'settings'));


-- >>> 0004_business.sql
-- =====================================================================
-- Business Portfolio additions (run after 0003_awards_sections.sql). Safe to re-run.
-- Second brand colour, new hero/about fields, counters and process steps.
-- =====================================================================

-- ---------- Settings: second brand colour (gradients) ----------
alter table site04.site_settings
  add column if not exists accent_color_2 text not null default '#14d4f0';

alter table site04.site_settings drop constraint if exists site_settings_accent_color_2_check;
alter table site04.site_settings add constraint site_settings_accent_color_2_check
  check (accent_color_2 ~* '^#([0-9a-f]{3}|[0-9a-f]{6})$');

-- ---------- Profile: hero + about content ----------
alter table site04.profile
  add column if not exists hero_headline text not null default '',
  add column if not exists trust_line text not null default '',
  add column if not exists hero_background_url text,
  add column if not exists about_title text not null default '',
  add column if not exists about_image_url text,
  add column if not exists about_points text[] not null default '{}',
  add column if not exists experience_years int not null default 0 check (experience_years between 0 and 80),
  add column if not exists work_photos jsonb not null default '[]'::jsonb;

-- ---------- Counters (About bars + numbers strip) ----------
create table if not exists site04.stats (
  id uuid primary key default gen_random_uuid(),
  value text not null,
  label text not null,
  placement text not null default 'band' check (placement in ('band', 'about')),
  percent int not null default 0 check (percent between 0 and 100),
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- Work process steps ----------
create table if not exists site04.process_steps (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null,
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
declare t text;
begin
  foreach t in array array['stats', 'process_steps'] loop
    execute format('drop trigger if exists trg_%1$s_updated on site04.%1$s', t);
    execute format('create trigger trg_%1$s_updated before update on site04.%1$s for each row execute function site04.set_updated_at()', t);
    execute format('alter table site04.%1$s enable row level security', t);
    execute format('drop policy if exists "public read %1$s" on site04.%1$s', t);
    execute format('drop policy if exists "admin insert %1$s" on site04.%1$s', t);
    execute format('drop policy if exists "admin update %1$s" on site04.%1$s', t);
    execute format('drop policy if exists "admin delete %1$s" on site04.%1$s', t);
    execute format('drop policy if exists "public read %1$s" on site04.%1$s', t);
    execute format('create policy "public read %1$s" on site04.%1$s for select using (active or site04.is_admin())', t);
    execute format('drop policy if exists "admin insert %1$s" on site04.%1$s', t);
    execute format('create policy "admin insert %1$s" on site04.%1$s for insert to authenticated with check (site04.is_admin())', t);
    execute format('drop policy if exists "admin update %1$s" on site04.%1$s', t);
    execute format('create policy "admin update %1$s" on site04.%1$s for update to authenticated using (site04.is_admin()) with check (site04.is_admin())', t);
    execute format('drop policy if exists "admin delete %1$s" on site04.%1$s', t);
    execute format('create policy "admin delete %1$s" on site04.%1$s for delete to authenticated using (site04.is_admin())', t);
  end loop;
end $$;


-- >>> 0005_cv.sql
-- =====================================================================
-- CV Portfolio additions (run after 0004_business.sql). Safe to re-run.
-- Personal info list, skill display styles, contact map and cursor switch.
-- =====================================================================

-- ---------- Profile: "Birthday / Age / Nationality …" rows on the About page ----------
alter table site04.profile
  add column if not exists personal_info jsonb not null default '[]'::jsonb;

-- ---------- Skills: bar, circle (languages) or tag (knowledge) ----------
alter table site04.skills
  add column if not exists display text not null default 'bar';

alter table site04.skills drop constraint if exists skills_display_check;
alter table site04.skills add constraint skills_display_check
  check (display in ('bar', 'circle', 'tag'));

-- ---------- Settings: contact map and animated mouse cursor ----------
alter table site04.site_settings
  add column if not exists map_embed_url text,
  add column if not exists cursor_enabled boolean not null default true;

-- Only Google Maps and OpenStreetMap embeds are allowed (they are the only frame sources in the CSP).
alter table site04.site_settings drop constraint if exists site_settings_map_embed_url_check;
alter table site04.site_settings add constraint site_settings_map_embed_url_check
  check (
    map_embed_url is null
    or map_embed_url = ''
    or map_embed_url ~* '^https://(www\.google\.com/maps/embed|maps\.google\.com/maps|www\.openstreetmap\.org/export/embed\.html)'
  );


-- >>> seed.sql (demo content)
-- Demo content for CV Portfolio (generated by scripts/generate-seed.ts).
-- Run AFTER all files in supabase/migrations (0001 – 0005).
-- Safe to re-run: it clears content tables first. Messages and admins are untouched.
begin;
truncate site04.site_settings, site04.profile, site04.services, site04.projects, site04.resume_items,
  site04.skills, site04.testimonials, site04.clients, site04.pricing_plans, site04.blog_posts, site04.awards,
  site04.stats, site04.process_steps;

insert into site04.site_settings (website_name, logo_url, accent_color, accent_color_2, default_theme, contact_email, public_phone, seo_title, seo_description, footer_text, hire_label, sections, map_embed_url, cursor_enabled) values
  ('Julian', null, '#f2b35b', '#f2b35b', 'dark', 'hello@julianhart.demo', '+49 30 1234 5678', 'Julian Hart — Web Developer & UI Designer', 'Julian Hart is a web developer and UI designer in Berlin building fast, beautiful websites and web apps for brands and startups.', 'Web developer & UI designer', 'Hire Me', '[]'::jsonb, 'https://www.openstreetmap.org/export/embed.html?bbox=13.3050%2C52.4870%2C13.5050%2C52.5570&layer=mapnik&marker=52.5200%2C13.4050', true);

insert into site04.profile (full_name, professional_title, typed_roles, short_intro, bio, email, phone, location, profile_image_url, hero_image_url, hero_headline, hero_background_url, resume_url, availability_status, trust_line, about_title, about_image_url, about_points, experience_years, work_photos, personal_info, social_links, skill_tools) values
  ('Julian Hart', 'Web Developer & UI Designer', array['Web Developer', 'UI Designer', 'Freelancer', 'Photographer']::text[], 'Creative developer based in Berlin, building fast and beautiful websites for brands, startups and people who love good design.', 'Hi, my name is Julian Hart. I have been designing and building websites for more than eight years, from simple landing pages to complete web apps with dashboards and online payments.

I love taking an idea from a rough sketch to a polished product. Clean code, clear design and fast pages are what I care about most — so my clients can focus on their business while their website quietly does its job.', 'hello@julianhart.demo', '+49 30 1234 5678', 'Berlin, Germany', '/demo/avatar-owner.svg', '/demo/portrait.svg', '', null, '/demo/julian-hart-cv.pdf', 'Available for freelance work', '', '', '/demo/about-wide.svg', array[]::text[], 8, '[]'::jsonb, '[{"label":"Birthday","value":"14.03.1994"},{"label":"Age","value":"32"},{"label":"Address","value":"Torstraße 18, Berlin"},{"label":"Email","value":"hello@julianhart.demo"},{"label":"Phone","value":"+49 30 1234 5678"},{"label":"Nationality","value":"German"},{"label":"Study","value":"TU Berlin"},{"label":"Degree","value":"Master"},{"label":"Interest","value":"Photography, Cycling"},{"label":"Freelance","value":"Available"}]'::jsonb, '[{"platform":"facebook","url":"https://facebook.com/"},{"platform":"x","url":"https://x.com/"},{"platform":"instagram","url":"https://instagram.com/"},{"platform":"dribbble","url":"https://dribbble.com/"},{"platform":"github","url":"https://github.com/"}]'::jsonb, '[]'::jsonb);

insert into site04.services (title, short_description, icon_key, active, sort_order) values
  ('Web Development', 'Fast, secure websites and web apps built with modern tools and easy to update from a dashboard.', 'monitor', true, 1),
  ('UI / UX Design', 'Clean, modern interfaces designed around your users, from wireframes to polished screens.', 'layers', true, 2),
  ('Mobile Friendly', 'Every page looks great and works smoothly on phones, tablets and large screens.', 'mobile', true, 3),
  ('Branding', 'Logo, colours and a consistent visual style that make your brand easy to remember.', 'palette', true, 4),
  ('SEO Optimisation', 'Solid technical SEO, fast loading and clear structure so people find you on Google.', 'search', true, 5),
  ('Photography', 'Portraits and product photos that give your website a real, personal feel.', 'camera', true, 6);

insert into site04.projects (title, slug, category, year, client, role, intro, challenge, solution, result, cover_image_url, gallery, live_url, likes, featured, status, sort_order) values
  ('Summit Outdoor Store', 'summit-outdoor-store', 'Web Design', 2026, 'Summit Gear', 'Design & Development', 'An online store for outdoor gear with quick checkout and a trip journal.', 'The client had a great product but an outdated website that was slow on mobile and hard to update. Visitors left before they understood what the product did.', 'We rewrote the key messages, designed a clean mobile-first layout and built it with a fast, modern stack. A simple dashboard lets the team edit every section on their own.', 'Pages now load in under a second, bounce rate dropped by a third and the team publishes new content every week without a developer.', '/demo/pf-mountains.svg', '["/demo/pf-mountains.svg","/demo/pf-workspace.svg"]'::jsonb, 'https://example.com', 240, true, 'published', 1),
  ('Lens & Light Studio', 'lens-and-light-studio', 'Photography', 2026, 'Lens & Light', 'Photography, Website', 'Portfolio website and photo shoot for a small photography studio.', 'The client had a great product but an outdated website that was slow on mobile and hard to update. Visitors left before they understood what the product did.', 'We rewrote the key messages, designed a clean mobile-first layout and built it with a fast, modern stack. A simple dashboard lets the team edit every section on their own.', 'Pages now load in under a second, bounce rate dropped by a third and the team publishes new content every week without a developer.', '/demo/pf-camera.svg', '["/demo/pf-camera.svg","/demo/pf-architecture.svg"]'::jsonb, null, 310, true, 'published', 2),
  ('Nord Coffee Identity', 'nord-coffee-identity', 'Branding', 2025, 'Nord Coffee', 'Brand Identity', 'Logo, packaging and a calm Nordic visual style for a speciality coffee brand.', 'The client had a great product but an outdated website that was slow on mobile and hard to update. Visitors left before they understood what the product did.', 'We rewrote the key messages, designed a clean mobile-first layout and built it with a fast, modern stack. A simple dashboard lets the team edit every section on their own.', 'Pages now load in under a second, bounce rate dropped by a third and the team publishes new content every week without a developer.', '/demo/pf-brand.svg', '["/demo/pf-brand.svg","/demo/pf-mobile.svg"]'::jsonb, null, 180, false, 'published', 3),
  ('Pulse Fitness App', 'pulse-fitness-app', 'Mobile App', 2025, 'Pulse', 'UI/UX Design', 'A workout tracker app with habit streaks and simple progress charts.', 'The client had a great product but an outdated website that was slow on mobile and hard to update. Visitors left before they understood what the product did.', 'We rewrote the key messages, designed a clean mobile-first layout and built it with a fast, modern stack. A simple dashboard lets the team edit every section on their own.', 'Pages now load in under a second, bounce rate dropped by a third and the team publishes new content every week without a developer.', '/demo/pf-mobile.svg', '["/demo/pf-mobile.svg","/demo/pf-brand.svg"]'::jsonb, 'https://example.com', 275, false, 'published', 4),
  ('Atlas Architects', 'atlas-architects', 'Web Design', 2024, 'Atlas Architects', 'Design & Development', 'A minimal portfolio website for an architecture office with large project galleries.', 'The client had a great product but an outdated website that was slow on mobile and hard to update. Visitors left before they understood what the product did.', 'We rewrote the key messages, designed a clean mobile-first layout and built it with a fast, modern stack. A simple dashboard lets the team edit every section on their own.', 'Pages now load in under a second, bounce rate dropped by a third and the team publishes new content every week without a developer.', '/demo/pf-architecture.svg', '["/demo/pf-architecture.svg","/demo/pf-mountains.svg"]'::jsonb, null, 205, false, 'published', 5),
  ('Remote Desk Dashboard', 'remote-desk-dashboard', 'Web Design', 2024, 'Remote Desk', 'Front-end Development', 'A booking dashboard for a co-working space with live desk availability.', 'The client had a great product but an outdated website that was slow on mobile and hard to update. Visitors left before they understood what the product did.', 'We rewrote the key messages, designed a clean mobile-first layout and built it with a fast, modern stack. A simple dashboard lets the team edit every section on their own.', 'Pages now load in under a second, bounce rate dropped by a third and the team publishes new content every week without a developer.', '/demo/pf-workspace.svg', '["/demo/pf-workspace.svg","/demo/pf-camera.svg"]'::jsonb, null, 190, false, 'published', 6);

insert into site04.resume_items (type, title, subtitle, period, badge, description, active, sort_order) values
  ('experience', 'Freelance Web Developer', 'Self-employed — Berlin', '2022 – Present', null, 'Websites, web apps and brand design for startups and small businesses across Europe.', true, 1),
  ('experience', 'Senior Front-end Developer', 'Pixelwerk Agency', '2019 – 2022', null, 'Led front-end work for e-commerce and SaaS clients and mentored two junior developers.', true, 2),
  ('experience', 'Web Designer', 'Studio Nord', '2017 – 2019', null, 'Designed and built landing pages, email templates and brand assets.', true, 3),
  ('education', 'Master in Computer Science', 'TU Berlin', '2015 – 2017', null, 'Focus on human–computer interaction and web technologies.', true, 1),
  ('education', 'Bachelor in Media Design', 'HTW Berlin', '2012 – 2015', null, 'Typography, visual design, photography and interactive media.', true, 2),
  ('education', 'UX Design Certificate', 'Interaction Design Foundation', '2020', null, 'User research, usability testing and design systems.', true, 3);

insert into site04.skills (name, category, display, level, active, sort_order) values
  ('HTML & CSS', 'Programming Skills', 'bar', 95, true, 1),
  ('JavaScript / TypeScript', 'Programming Skills', 'bar', 88, true, 2),
  ('React & Next.js', 'Programming Skills', 'bar', 85, true, 3),
  ('Figma', 'Design Skills', 'bar', 90, true, 4),
  ('Photoshop', 'Design Skills', 'bar', 78, true, 5),
  ('Branding', 'Design Skills', 'bar', 72, true, 6),
  ('German', 'Language Skills', 'circle', 100, true, 7),
  ('English', 'Language Skills', 'circle', 90, true, 8),
  ('Spanish', 'Language Skills', 'circle', 55, true, 9),
  ('Website hosting', 'Knowledge', 'tag', 0, true, 10),
  ('iOS and Android apps', 'Knowledge', 'tag', 0, true, 11),
  ('Create logo design', 'Knowledge', 'tag', 0, true, 12),
  ('Design for print', 'Knowledge', 'tag', 0, true, 13),
  ('Modern and mobile-ready', 'Knowledge', 'tag', 0, true, 14),
  ('Advertising services', 'Knowledge', 'tag', 0, true, 15);

insert into site04.testimonials (name, role, company, project_title, quote, avatar_url, rating, active, sort_order) values
  ('Sofia Lindqvist', 'Founder', 'Nord Coffee', 'Brand Identity', 'Julian understood our brand from the first call. The new identity and website feel exactly like us — calm, simple and warm.', '/demo/avatar-1.svg', 5, true, 1),
  ('Marcus Bell', 'CEO', 'Summit Gear', 'Online Store', 'Fast, reliable and full of good ideas. Our online sales grew 35% in the first three months after launch.', '/demo/avatar-2.svg', 5, true, 2),
  ('Emma Novak', 'Product Manager', 'Pulse', 'Fitness App', 'The app design is clean and easy to use. Julian was always on time and explained every decision clearly.', '/demo/avatar-3.svg', 5, true, 3);

insert into site04.clients (name, category, logo_url, website_url, active, sort_order) values
  ('Nord', 'Brand', '/demo/logo-nord.svg', null, true, 1),
  ('Atlas', 'Brand', '/demo/logo-atlas.svg', null, true, 2),
  ('Lumen', 'Brand', '/demo/logo-lumen.svg', null, true, 3),
  ('Kite', 'Brand', '/demo/logo-kite.svg', null, true, 4),
  ('Orbit', 'Brand', '/demo/logo-orbit.svg', null, true, 5),
  ('Vela', 'Brand', '/demo/logo-vela.svg', null, true, 6);

insert into site04.awards (title, organization, year, short_description, image_url, link_url, active, sort_order) values
  ('Site of the Day', 'Awwwards', '2026', 'For the Summit Outdoor Store website — design, usability and creativity.', '/demo/award-1.svg', null, true, 1),
  ('Top Rated Freelancer', 'Upwork', '2025', 'Top 3% of freelancers for five-star client feedback and on-time delivery.', '/demo/award-2.svg', null, true, 2),
  ('Certified UX Designer', 'IxDF', '2024', 'Professional certificate in user experience and interaction design.', '/demo/award-3.svg', null, true, 3);

insert into site04.pricing_plans (name, tagline, price, period, description, features, cta_label, highlighted, active, sort_order) values
  ('Basic', 'Landing page', '$690', 'one-time', 'A single, beautiful page to present you or your product.', array['1 responsive page', 'Contact form', 'Basic SEO', '5-day delivery']::text[], 'Choose Plan', false, true, 1),
  ('Standard', 'Most popular', '$1,900', 'one-time', 'A complete website with admin dashboard, blog and SEO.', array['Up to 6 pages', 'Admin dashboard', 'Blog & SEO setup', 'Speed optimisation', '30 days support']::text[], 'Choose Plan', true, true, 2),
  ('Premium', 'Web app', '$4,500', 'starting from', 'Custom web apps with accounts, payments and integrations.', array['Custom features', 'User accounts', 'Online payments', 'API integrations', '90 days support']::text[], 'Choose Plan', false, true, 3);

insert into site04.blog_posts (title, slug, excerpt, content, cover_image_url, category, read_time, published_at, status) values
  ('Format releases a new tool that makes portfolio hosting simple', 'new-tool-portfolio-hosting', 'A quick look at the new wave of simple hosting tools for designers and developers — and what they mean for your portfolio.', 'Hosting a portfolio used to mean servers, FTP and a lot of patience. Today it takes a few clicks.

## Why it matters
Your portfolio is often the first thing a client sees. If it is slow or broken, you lose the job before the first call.

## What to look for
- Automatic HTTPS
- Deploys from GitHub
- A free plan for small sites

## My setup
I use Next.js, a small database for content and a hosting platform that deploys every push automatically. Updates take seconds, not hours.', '/demo/news-sneakers.svg', 'Tools', '4 min read', '2026-09-18', 'published'),
  ('How I find direction when starting a new design', 'finding-direction-new-design', 'Blank canvas? These five questions help me pick a clear direction before I open Figma.', 'Every project starts with a blank page. These questions help me move forward quickly.

## 1. Who is it for?
A website for teenagers looks very different from one for lawyers.

## 2. What is the one action?
Book a call, buy a product, read an article — pick one.

## 3. What should it feel like?
Three words, for example calm, bold and friendly.

## 4. What do competitors do?
Look, learn and then do something different.

## 5. What content exists?
Design around real text and photos, never lorem ipsum.', '/demo/news-compass.svg', 'Design', '5 min read', '2026-09-02', 'published'),
  ('Why small details make websites feel alive', 'small-details-websites-alive', 'Hover effects, smooth scrolling and a custom cursor — small touches that make a big difference.', 'Good websites are not only about layout and colour. Small details make them feel alive.

## Motion with purpose
Animations should guide the eye, not distract it. Keep them short and smooth.

## Feedback everywhere
Buttons that react, forms that confirm and links that change on hover all tell users the site is listening.

## Respect the user
Always turn heavy motion off for people who prefer reduced motion in their system settings.', '/demo/news-cat.svg', 'Web Design', '3 min read', '2026-08-20', 'published'),
  ('A calm home studio setup for focused work', 'calm-home-studio-setup', 'The simple desk, light and tools I use every day to stay focused while working from home.', 'A good workspace does not need to be expensive. It needs to be calm.

## Light
Warm, indirect light in the evening and daylight during the day.

## One screen
A single large monitor keeps me focused on one task at a time.

## Sound
Good headphones and a simple playlist without lyrics.

## Routine
The same start time and a short walk before work make the biggest difference of all.', '/demo/news-studio.svg', 'Lifestyle', '3 min read', '2026-08-04', 'published');

insert into site04.stats (value, label, placement, percent, active, sort_order) values
  ('8+', 'Years of experience', 'band', 0, true, 1),
  ('140+', 'Projects completed', 'band', 0, true, 2),
  ('90+', 'Happy clients', 'band', 0, true, 3),
  ('12', 'Awards won', 'band', 0, true, 4);

insert into site04.process_steps (title, description, active, sort_order) values
  ('Discuss', 'A short call to understand your goals, audience and budget.', true, 1),
  ('Design', 'Wireframes and visual design you can review and comment on.', true, 2),
  ('Develop', 'Clean, fast code with weekly previews on a live link.', true, 3),
  ('Launch', 'Go live, then support and small updates when you need them.', true, 4);

commit;

-- ------------------------------------------------------------------
-- Make your dashboard owner (run once, after creating the user in
-- Supabase -> Authentication -> Users). Replace the email below.
-- ------------------------------------------------------------------
-- insert into site04.admins (user_id, display_name)
-- select id, 'Julian Hart' from auth.users where email = 'owner@example.com'
-- on conflict (user_id) do update set active = true;


-- Tables that already existed before a re-run keep their grants; make sure they are set.
grant select, insert, update, delete on all tables in schema site04 to anon, authenticated, service_role;
revoke update on site04.admins from anon, authenticated;
grant update (display_name, avatar_url) on site04.admins to authenticated;

-- Make the dashboard owner for THIS website (create the user first in Authentication → Users):
-- insert into site04.admins (user_id, display_name)
-- select id, 'Owner Name' from auth.users where email = 'owner@example.com'
-- on conflict (user_id) do update set active = true;
